// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVOd1V9z1OLyMSXZWyWGPBLOGeSL1NZUs',
    appId: '1:836886861033:web:838c13fa58468b3c4d8c78',
    messagingSenderId: '836886861033',
    projectId: 'sutlej-club-5df76',
    authDomain: 'sutlej-club-5df76.firebaseapp.com',
    storageBucket: 'sutlej-club-5df76.appspot.com',
    measurementId: 'G-W2141TRXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplAxWixgG5VC0sBP8ENqCx8fhxuD-tkQ',
    appId: '1:836886861033:android:b7962d65d82cdd974d8c78',
    messagingSenderId: '836886861033',
    projectId: 'sutlej-club-5df76',
    storageBucket: 'sutlej-club-5df76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2A928HxgG24KhsObdUckamm5T_gQlyw',
    appId: '1:836886861033:ios:8668f70f21bd19e14d8c78',
    messagingSenderId: '836886861033',
    projectId: 'sutlej-club-5df76',
    storageBucket: 'sutlej-club-5df76.appspot.com',
    iosClientId: '836886861033-s3mtrgi3erdp7pmob1fvsdomc4dgacti.apps.googleusercontent.com',
    iosBundleId: 'com.auribises.sutlejClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2A928HxgG24KhsObdUckamm5T_gQlyw',
    appId: '1:836886861033:ios:2f46d100085d4dd74d8c78',
    messagingSenderId: '836886861033',
    projectId: 'sutlej-club-5df76',
    storageBucket: 'sutlej-club-5df76.appspot.com',
    iosClientId: '836886861033-nnhjpliuta49uv6bu0bd0csviio2cgju.apps.googleusercontent.com',
    iosBundleId: 'com.auribises.sutlejClub.RunnerTests',
  );
}
